name: Test build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.11"
        # see https://github.com/tox-dev/tox-uv/issues/110
        python-version: 3.13

    - name: Install tox
      run: uv tool install tox

    - name: Run tests with tox
      run: tox
